//
//  Disciplin.swift
//  Leichatletik
//
//  Created by Lukas Schmidt on 02.02.17.
//  Copyright © 2017 freiraum. All rights reserved.
//

public struct Disciplin: Hashable, Sendable {
    
    public enum Unit: Sendable {
        case punkte
        case zeit
        case metrisch
        case unknown
    }
    
    public let name: String
    public let shortName: String
    public let code: String
    public let dlvID: String
    public let unit: Unit

    public init(dlvID: String) {
        if let newSelf = Disciplin.all.first(where: { $0.dlvID == dlvID || $0.code == dlvID }) {
            self = newSelf
        } else {
            self.name = dlvID
            self.shortName = dlvID
            self.code = dlvID
            self.dlvID = dlvID
            self.unit = .unknown
        }
    }
    
    public init(code: String) {
        if let newSelf = Disciplin.all.first(where: { $0.code == code }) {
            self = newSelf
        } else {
            self.name = code
            self.shortName = code
            self.code = code
            self.dlvID = code
            self.unit = .unknown
        }
    }
    
    public init(name: String, shortName: String, code: String, dlvID: String, unit: Unit) {
        self.name = name
        self.shortName = shortName
        self.code = code
        self.dlvID = dlvID
        self.unit = unit
    }
    
    public static let all: [Disciplin] = [
        Disciplin(name: "DMM Gruppe 1", shortName: "DMM G.1", code: "ADM1", dlvID: "DM1", unit: .punkte),
        Disciplin(name: "DMM Gruppe 2", shortName: "DMM G.2", code: "ADM2", dlvID: "DM2", unit: .punkte),
        Disciplin(name: "DMM Gruppe 3", shortName: "DMM G.3", code: "ADM3", dlvID: "DM3", unit: .punkte),
        Disciplin(name: "DMM Gruppe 4", shortName: "DMM G.4", code: "ADM4", dlvID: "DM4", unit: .punkte),
        Disciplin(name: "Team DM", shortName: "Team DM", code: "ADMT", dlvID: "DMT", unit: .punkte),
        Disciplin(name: "30 m", shortName: "30m", code: "L30", dlvID: "30", unit: .zeit),
        Disciplin(name: "30 m fliegend", shortName: "30m flieg.", code: "L30F", dlvID: "30F", unit: .zeit),
        Disciplin(name: "40 m", shortName: "40m", code: "L40", dlvID: "40", unit: .zeit),
        Disciplin(name: "50 m", shortName: "50m", code: "L50", dlvID: "50", unit: .zeit),
        Disciplin(name: "60 m", shortName: "60m", code: "L60", dlvID: "60", unit: .zeit),
        Disciplin(name: "75 m", shortName: "75m", code: "L75", dlvID: "75", unit: .zeit),
        Disciplin(name: "80 m", shortName: "80m", code: "L80", dlvID: "80", unit: .zeit),
        Disciplin(name: "100 m", shortName: "100m", code: "L100", dlvID: "100", unit: .zeit),
        Disciplin(name: "150 m", shortName: "150m", code: "L150", dlvID: "150", unit: .zeit),
        Disciplin(name: "200 m", shortName: "200m", code: "L200", dlvID: "200", unit: .zeit),
        Disciplin(name: "300 m", shortName: "300m", code: "L300", dlvID: "300", unit: .zeit),
        Disciplin(name: "400 m", shortName: "400m", code: "L400", dlvID: "400", unit: .zeit),
        Disciplin(name: "500 m", shortName: "500m", code: "L500", dlvID: "500", unit: .zeit),
        Disciplin(name: "600 m", shortName: "600m", code: "L600", dlvID: "600", unit: .zeit),
        Disciplin(name: "800 m", shortName: "800m", code: "L800", dlvID: "800", unit: .zeit),
        Disciplin(name: "1.000 m", shortName: "1.000m", code: "L1K0", dlvID: "1K0", unit: .zeit),
        Disciplin(name: "1.500 m", shortName: "1.500m", code: "L1K5", dlvID: "1K5", unit: .zeit),
        Disciplin(name: "1 Meile", shortName: "1 Meile", code: "LMEI", dlvID: "MEI", unit: .zeit),
        Disciplin(name: "2.000 m", shortName: "2.000m", code: "L2K0", dlvID: "2K0", unit: .zeit),
        Disciplin(name: "3.000 m", shortName: "3.000m", code: "L3K0", dlvID: "3K0", unit: .zeit),
        Disciplin(name: "2 Meilen", shortName: "2 Meilen", code: "L2MEI", dlvID: "2MEI", unit: .zeit),
        Disciplin(name: "5.000 m", shortName: "5.000m", code: "L5K0", dlvID: "5K0", unit: .zeit),
        Disciplin(name: "10.000 m", shortName: "10.000m", code: "L10K", dlvID: "10K", unit: .zeit),
        Disciplin(name: "3 km Straße", shortName: "3km Str.", code: "S3K", dlvID: "3S", unit: .zeit),
        Disciplin(name: "3 km Straße Mannschaft", shortName: "3km Str.M.", code: "S3KM", dlvID: "3M", unit: .zeit),
        Disciplin(name: "5 km Straße", shortName: "5km Str.", code: "S5K", dlvID: "5S", unit: .zeit),
        Disciplin(name: "5 km Straße Mannschaft", shortName: "5km Str.M.", code: "S5KM", dlvID: "5M", unit: .zeit),
        Disciplin(name: "7,5 km Straße", shortName: "7,5km Str.", code: "S7K5", dlvID: "7K5S", unit: .zeit),
        Disciplin(name: "7,5 km Straße Mannschaft", shortName: "7,5kmStr.M", code: "S7K5M", dlvID: "7K5M", unit: .zeit),
        Disciplin(name: "10 km Straße", shortName: "10km Str.", code: "S10K", dlvID: "10S", unit: .zeit),
        Disciplin(name: "10 km Straße Mannschaft", shortName: "10km Str.M", code: "S10KM", dlvID: "10M", unit: .zeit),
        Disciplin(name: "15 km Straße", shortName: "15km Str.", code: "S15K", dlvID: "15S", unit: .zeit),
        Disciplin(name: "15 km Straße Mannschaft", shortName: "15km Str.M", code: "S15KM", dlvID: "15M", unit: .zeit),
        Disciplin(name: "20 km Straße", shortName: "20km Str.", code: "S20K", dlvID: "20S", unit: .zeit),
        Disciplin(name: "20 km Straße Mannschaft", shortName: "20km Str.M", code: "S20KM", dlvID: "20M", unit: .zeit),
        Disciplin(name: "Halbmarathon", shortName: "HM", code: "SHAL", dlvID: "HAL", unit: .zeit),
        Disciplin(name: "Halbmarathon Mannschaft", shortName: "HM Man.", code: "SHALM", dlvID: "HALM", unit: .zeit),
        Disciplin(name: "25 km Straße", shortName: "25km Str.", code: "S25K", dlvID: "25S", unit: .zeit),
        Disciplin(name: "25 km Straße Mannschaft", shortName: "25km Str.M", code: "S25KM", dlvID: "25M", unit: .zeit),
        Disciplin(name: "Marathon", shortName: "Marathon", code: "SMAR", dlvID: "MAR", unit: .zeit),
        Disciplin(name: "Marathon Mannschaft", shortName: "Marathon M", code: "SMARM", dlvID: "MARM", unit: .zeit),
        Disciplin(name: "50 km Straße", shortName: "50km Str.", code: "S50K", dlvID: "50S", unit: .zeit),
        Disciplin(name: "50 km Straße Mannschaft", shortName: "50kmStr.M", code: "S50KM", dlvID: "50M", unit: .zeit),
        Disciplin(name: "100 km Straße", shortName: "100km Str.", code: "S100K", dlvID: "100S", unit: .zeit),
        Disciplin(name: "100 km Straße Mannschaft", shortName: "100kmStr.M", code: "S100KM", dlvID: "100M", unit: .zeit),
        Disciplin(name: "Volkslauf", shortName: "Volkslauf", code: "SVOL", dlvID: "VOL", unit: .zeit),
        Disciplin(name: "Volkslauf Mannschaft", shortName: "Volksl. M.", code: "SVOLM", dlvID: "VOLM", unit: .zeit),
        Disciplin(name: "Berglauf", shortName: "Brgl.", code: "SBRG", dlvID: "BRG", unit: .zeit),
        Disciplin(name: "Berglauf Mannschaft", shortName: "Brgl. Man.", code: "SBRGM", dlvID: "BRGM", unit: .zeit),
        Disciplin(name: "Crosslauf", shortName: "Crs. Lauf", code: "SCR", dlvID: "CROS", unit: .zeit),
        Disciplin(name: "Crosslauf kurz", shortName: "Crs. kurz", code: "SCRK", dlvID: "CROK", unit: .zeit),
        Disciplin(name: "Crosslauf lang", shortName: "Crs. lang", code: "SCRL", dlvID: "CROL", unit: .zeit),
        Disciplin(name: "Cross Sprint", shortName: "Crs.Sprint", code: "SCRS", dlvID: "CRSS", unit: .zeit),
        Disciplin(name: "Straßenlauf", shortName: "Str.-lauf", code: "SL", dlvID: "SL", unit: .zeit),
        Disciplin(name: "Straßenlauf kurz", shortName: "Str. kurz", code: "SLK", dlvID: "SLK", unit: .zeit),
        Disciplin(name: "Straßenlauf lang", shortName: "Str. lang", code: "SLL", dlvID: "SLL", unit: .zeit),
        Disciplin(name: "Waldlauf", shortName: "Waldlauf", code: "SWLD", dlvID: "WLD", unit: .zeit),
        Disciplin(name: "Walking", shortName: "Walking", code: "SWALKING", dlvID: "WALK", unit: .zeit),
        Disciplin(name: "Nordic Walking", shortName: "N-Walking", code: "SNWALKING", dlvID: "NWLK", unit: .zeit),
        Disciplin(name: "Wandern", shortName: "Wandern", code: "SWANDERN", dlvID: "WAND", unit: .zeit),
        Disciplin(name: "Inline-Skating", shortName: "Inline", code: "SINLINE", dlvID: "INLN", unit: .zeit),
        Disciplin(name: "Rollstuhl", shortName: "Rollstuhl", code: "SROLLSTUHL", dlvID: "ROLL", unit: .zeit),
        Disciplin(name: "Walking/Nordic Walking (gleiche Streckenlänge)", shortName: "Walk./N-W.", code: "SWANDERNWALKING", dlvID: "WANW", unit: .zeit),
        Disciplin(name: "Sonstiges", shortName: "Sonstiges", code: "SSONSTIGES", dlvID: "SONS", unit: .zeit),
        Disciplin(name: "30 m Hürden", shortName: "30m Hürd.", code: "H30", dlvID: "30H", unit: .zeit),
        Disciplin(name: "50 m Hürden", shortName: "50m Hürd.", code: "H50", dlvID: "50H", unit: .zeit),
        Disciplin(name: "60 m Hürden", shortName: "60m Hürd.", code: "H60", dlvID: "60H", unit: .zeit),
        Disciplin(name: "60 m Hürden 0,600 m", shortName: "60m Hürd.", code: "H60_0600", dlvID: "60H", unit: .zeit),
        Disciplin(name: "60 m Hürden 0,686 m", shortName: "60m Hürd.", code: "H60_0686", dlvID: "60H", unit: .zeit),
        Disciplin(name: "60 m Hürden 0,762 m", shortName: "60m Hürd.", code: "H60_0762", dlvID: "60H", unit: .zeit),
        Disciplin(name: "60 m Hürden 0,838 m", shortName: "60m Hürd.", code: "H60_0838", dlvID: "60H", unit: .zeit),
        Disciplin(name: "60 m Hürden 0,914 m", shortName: "60m Hürd.", code: "H60_0914", dlvID: "60H", unit: .zeit),
        Disciplin(name: "60 m Hürden 0,991 m", shortName: "60m Hürd.", code: "H60_0991", dlvID: "60H", unit: .zeit),
        Disciplin(name: "60 m Hürden 1,067 m", shortName: "60m Hürd.", code: "H60_1067", dlvID: "60H", unit: .zeit),
        Disciplin(name: "80 m Hürden", shortName: "80m Hürd.", code: "H80", dlvID: "80H", unit: .zeit),
        Disciplin(name: "80 m Hürden 0,686 m", shortName: "80m Hürd.", code: "H80_0686", dlvID: "80H", unit: .zeit),
        Disciplin(name: "80 m Hürden 0,762 m", shortName: "80m Hürd.", code: "H80_0762", dlvID: "80H", unit: .zeit),
        Disciplin(name: "80 m Hürden 0,838 m", shortName: "80m Hürd.", code: "H80_0838", dlvID: "80H", unit: .zeit),
        Disciplin(name: "100 m Hürden", shortName: "100m Hürd.", code: "H100", dlvID: "100H", unit: .zeit),
        Disciplin(name: "100 m Hürden 0,686 m", shortName: "100m Hürd.", code: "H100_0686", dlvID: "100H", unit: .zeit),
        Disciplin(name: "100 m Hürden 0,762 m", shortName: "100m Hürd.", code: "H100_0762", dlvID: "100H", unit: .zeit),
        Disciplin(name: "100 m Hürden 0,838 m", shortName: "100m Hürd.", code: "H100_0838", dlvID: "100H", unit: .zeit),
        Disciplin(name: "100 m Hürden 0,914 m", shortName: "100m Hürd.", code: "H100_0914", dlvID: "100H", unit: .zeit),
        Disciplin(name: "110 m Hürden", shortName: "110m Hürd.", code: "H110", dlvID: "110H", unit: .zeit),
        Disciplin(name: "110 m Hürden 0,686 m", shortName: "110m Hürd.", code: "H110_0686", dlvID: "110H", unit: .zeit),
        Disciplin(name: "110 m Hürden 0,762 m", shortName: "110m Hürd.", code: "H110_0762", dlvID: "110H", unit: .zeit),
        Disciplin(name: "110 m Hürden 0,838 m", shortName: "110m Hürd.", code: "H110_0838", dlvID: "110H", unit: .zeit),
        Disciplin(name: "110 m Hürden 0,914 m", shortName: "110m Hürd.", code: "H110_0914", dlvID: "110H", unit: .zeit),
        Disciplin(name: "110 m Hürden 0,991 m", shortName: "110m Hürd.", code: "H110_0991", dlvID: "110H", unit: .zeit),
        Disciplin(name: "110 m Hürden 1,067 m", shortName: "110m Hürd.", code: "H110_1067", dlvID: "110H", unit: .zeit),
        Disciplin(name: "200 m Hürden", shortName: "200m Hürd.", code: "H200", dlvID: "200H", unit: .zeit),
        Disciplin(name: "300 m Hürden", shortName: "300m Hürd.", code: "H300", dlvID: "300H", unit: .zeit),
        Disciplin(name: "300 m Hürden 0,686 m", shortName: "300m Hürd.", code: "H300_0686", dlvID: "300H", unit: .zeit),
        Disciplin(name: "300 m Hürden 0,762 m", shortName: "300m Hürd.", code: "H300_0762", dlvID: "300H", unit: .zeit),
        Disciplin(name: "300 m Hürden 0,838 m", shortName: "300m Hürd.", code: "H300_0838", dlvID: "300H", unit: .zeit),
        Disciplin(name: "300 m Hürden 0,914 m", shortName: "300m Hürd.", code: "H300_0914", dlvID: "300H", unit: .zeit),
        Disciplin(name: "400 m Hürden", shortName: "400m Hürd.", code: "H400", dlvID: "400H", unit: .zeit),
        Disciplin(name: "400 m Hürden 0,762 m", shortName: "400m Hürd.", code: "H400_0762", dlvID: "400H", unit: .zeit),
        Disciplin(name: "400 m Hürden 0,838 m", shortName: "400m Hürd.", code: "H400_0838", dlvID: "400H", unit: .zeit),
        Disciplin(name: "400 m Hürden 0,914 m", shortName: "400m Hürd.", code: "H400_0914", dlvID: "400H", unit: .zeit),
        Disciplin(name: "1.500 m Hindernis", shortName: "1.500m Hin", code: "H1K5", dlvID: "1K5H", unit: .zeit),
        Disciplin(name: "1.500 m Hindernis 0,762 m", shortName: "1.500m Hin", code: "H1K5_0762", dlvID: "1K5H", unit: .zeit),
        Disciplin(name: "2.000 m Hindernis", shortName: "2.000m Hin", code: "H2K0", dlvID: "2K0H", unit: .zeit),
        Disciplin(name: "2.000 m Hindernis 0,762 m", shortName: "2.000m Hin", code: "H2K0_0762", dlvID: "2K0H", unit: .zeit),
        Disciplin(name: "2.000 m Hindernis 0,838 m", shortName: "2.000m Hin", code: "H2K0_0838", dlvID: "2K0H", unit: .zeit),
        Disciplin(name: "2.000 m Hindernis 0,914 m", shortName: "2.000m Hin", code: "H2K0_0914", dlvID: "2K0H", unit: .zeit),
        Disciplin(name: "3.000 m Hindernis", shortName: "3.000m Hin", code: "H3K0", dlvID: "3K0H", unit: .zeit),
        Disciplin(name: "3.000 m Hindernis 0,762 m", shortName: "3.000m Hin", code: "H3K0_0762", dlvID: "3K0H", unit: .zeit),
        Disciplin(name: "3.000 m Hindernis 0,914 m", shortName: "3.000m Hin", code: "H3K0_0914", dlvID: "3K0H", unit: .zeit),
        Disciplin(name: "4x50 m Staffel", shortName: "4x50m", code: "X4X5", dlvID: "4X5", unit: .zeit),
        Disciplin(name: "4x60 m Staffel", shortName: "4x60m", code: "X4X6", dlvID: "4X6", unit: .zeit),
        Disciplin(name: "4x75 m Staffel", shortName: "4x75m", code: "X4X7", dlvID: "4X7", unit: .zeit),
        Disciplin(name: "3x100 m Staffel", shortName: "3x100m", code: "X3X100", dlvID: "3X1S", unit: .zeit),
        Disciplin(name: "4x100 m Staffel", shortName: "4x100m", code: "X4X1", dlvID: "4X1", unit: .zeit),
        Disciplin(name: "4x200 m Staffel", shortName: "4x200m", code: "X4X2", dlvID: "4X2", unit: .zeit),
        Disciplin(name: "4x400 m Staffel", shortName: "4x400m", code: "X4X4", dlvID: "4X4", unit: .zeit),
        Disciplin(name: "3x800 m Staffel", shortName: "3x800m", code: "X3X8", dlvID: "3X8", unit: .zeit),
        Disciplin(name: "4x800 m Staffel", shortName: "4x800m", code: "X4X8", dlvID: "4X8", unit: .zeit),
        Disciplin(name: "3x1.000 m Staffel", shortName: "3x1.000m", code: "X3X1", dlvID: "3X1", unit: .zeit),
        Disciplin(name: "4x1.500 m Staffel", shortName: "4x1.500m", code: "X4X15", dlvID: "4X15", unit: .zeit),
        Disciplin(name: "6x50 m Staffel", shortName: "6x50m", code: "X6X5", dlvID: "6X5", unit: .zeit),
        Disciplin(name: "8x50 m Staffel", shortName: "8x50m", code: "X8X5", dlvID: "8X5", unit: .zeit),
        Disciplin(name: "Olympische Staffel", shortName: "Olymp.Stf.", code: "XOLY", dlvID: "OLY", unit: .zeit),
        Disciplin(name: "Marathonstaffel", shortName: "Mar.Stfl.", code: "XMARS", dlvID: "MARS", unit: .zeit),
        Disciplin(name: "Pendelstaffel", shortName: "Pndlstfl.", code: "XPEN", dlvID: "PEN", unit: .zeit),
        Disciplin(name: "Schwedenstaffel", shortName: "Schwedens.", code: "XSWE", dlvID: "SWE", unit: .zeit),
        Disciplin(name: "4x110/100 m Hürden Staffel", shortName: "4xHürden", code: "X4XH", dlvID: "4XH", unit: .zeit),
        Disciplin(name: "1.000 m Bahngehen", shortName: "1.000m BG", code: "GB1", dlvID: "1G", unit: .zeit),
        Disciplin(name: "2.000 m Bahngehen", shortName: "2.000m BG", code: "GB2", dlvID: "2G", unit: .zeit),
        Disciplin(name: "3.000 m Bahngehen", shortName: "3.000m BG", code: "GB3", dlvID: "3G", unit: .zeit),
        Disciplin(name: "5.000 m Bahngehen", shortName: "5.000m BG", code: "GB5", dlvID: "5G", unit: .zeit),
        Disciplin(name: "10.000 m Bahngehen", shortName: "10.000m BG", code: "GB10", dlvID: "10G", unit: .zeit),
        Disciplin(name: "20.000 m Bahngehen", shortName: "20.000m BG", code: "GB20", dlvID: "20G", unit: .zeit),
        Disciplin(name: "50.000 m Bahngehen", shortName: "50.000m BG", code: "GB50", dlvID: "50G", unit: .zeit),
        Disciplin(name: "1 km Straßengehen", shortName: "1km SG", code: "GS1", dlvID: "1GS", unit: .zeit),
        Disciplin(name: "1 km Straßengehen Mannschaft", shortName: "1km SG M.", code: "GS1M", dlvID: "1GM", unit: .zeit),
        Disciplin(name: "2 km Straßengehen", shortName: "2km SG", code: "GS2", dlvID: "2GS", unit: .zeit),
        Disciplin(name: "2 km Straßengehen Mannschaft", shortName: "2km SG M.", code: "GS2M", dlvID: "2GM", unit: .zeit),
        Disciplin(name: "3 km Straßengehen", shortName: "3km SG", code: "GS3", dlvID: "3GS", unit: .zeit),
        Disciplin(name: "3 km Straßengehen Mannschaft", shortName: "3km SG M.", code: "GS3M", dlvID: "3GM", unit: .zeit),
        Disciplin(name: "5 km Straßengehen", shortName: "5km SG", code: "GS5", dlvID: "5GS", unit: .zeit),
        Disciplin(name: "5 km Straßengehen Mannschaft", shortName: "5km SG M.", code: "GS5M", dlvID: "5GM", unit: .zeit),
        Disciplin(name: "10 km Straßengehen", shortName: "10km SG", code: "GS10", dlvID: "10GS", unit: .zeit),
        Disciplin(name: "10 km Straßengehen Mannschaft", shortName: "10km SG M.", code: "GS10M", dlvID: "10GM", unit: .zeit),
        Disciplin(name: "20 km Straßengehen", shortName: "20km SG", code: "GS20", dlvID: "20GS", unit: .zeit),
        Disciplin(name: "20 km Straßengehen Mannschaft", shortName: "20km SG M.", code: "GS20M", dlvID: "20GM", unit: .zeit),
        Disciplin(name: "30 km Straßengehen", shortName: "30km SG", code: "GS30", dlvID: "30GS", unit: .zeit),
        Disciplin(name: "30 km Straßengehen Mannschaft", shortName: "30km SG M.", code: "GS30M", dlvID: "30GM", unit: .zeit),
        Disciplin(name: "35 km Straßengehen", shortName: "35km SG", code: "GS35", dlvID: "35GS", unit: .zeit),
        Disciplin(name: "35 km Straßengehen Mannschaft", shortName: "35km SG M.", code: "GS35M", dlvID: "35GM", unit: .zeit),
        Disciplin(name: "50 km Straßengehen", shortName: "50km SG", code: "GS50", dlvID: "50GS", unit: .zeit),
        Disciplin(name: "50 km Straßengehen Mannschaft", shortName: "50km SG M.", code: "GS50M", dlvID: "50GM", unit: .zeit),
        Disciplin(name: "Hochsprung", shortName: "Hoch", code: "THOC", dlvID: "HOC", unit: .metrisch),
        Disciplin(name: "Stabhochsprung", shortName: "Stab", code: "TSTA", dlvID: "STA", unit: .metrisch),
        Disciplin(name: "Standweitsprung", shortName: "Standweit", code: "TSTW", dlvID: "STW", unit: .metrisch),
        Disciplin(name: "Weitsprung", shortName: "Weit", code: "TWEI", dlvID: "WEI", unit: .metrisch),
        Disciplin(name: "Weitsprungzone", shortName: "Weitzone", code: "TWEZ", dlvID: "WEZ", unit: .metrisch),
        Disciplin(name: "Dreisprung", shortName: "Dreispr.", code: "TDRE", dlvID: "DRE", unit: .metrisch),
        Disciplin(name: "Kugelstoß", shortName: "Kugel", code: "TKUG", dlvID: "KUG", unit: .metrisch),
        Disciplin(name: "Kugelstoß 2 kg", shortName: "Kugel 2", code: "TKUG_2000", dlvID: "KUG", unit: .metrisch),
        Disciplin(name: "Kugelstoß 3 kg", shortName: "Kugel 3", code: "TKUG_3000", dlvID: "KUG", unit: .metrisch),
        Disciplin(name: "Kugelstoß 4 kg", shortName: "Kugel 4", code: "TKUG_4000", dlvID: "KUG", unit: .metrisch),
        Disciplin(name: "Kugelstoß 5 kg", shortName: "Kugel 5", code: "TKUG_5000", dlvID: "KUG", unit: .metrisch),
        Disciplin(name: "Kugelstoß 6 kg", shortName: "Kugel 6", code: "TKUG_6000", dlvID: "KUG", unit: .metrisch),
        Disciplin(name: "Kugelstoß 7,26 kg", shortName: "Kugel 7", code: "TKUG_7260", dlvID: "KUG", unit: .metrisch),
        Disciplin(name: "Gewichtwurf", shortName: "Gewicht", code: "TGEW", dlvID: "GEW", unit: .metrisch),
        Disciplin(name: "Gewichtwurf 3 kg", shortName: "Gew. 3", code: "TGEW_03000", dlvID: "GEW", unit: .metrisch),
        Disciplin(name: "Gewichtwurf 4 kg", shortName: "Gew. 4", code: "TGEW_04000", dlvID: "GEW", unit: .metrisch),
        Disciplin(name: "Gewichtwurf 5 kg", shortName: "Gew. 5", code: "TGEW_05000", dlvID: "GEW", unit: .metrisch),
        Disciplin(name: "Gewichtwurf 5,45 kg", shortName: "Gew. 5,45", code: "TGEW_05450", dlvID: "GEW", unit: .metrisch),
        Disciplin(name: "Gewichtwurf 7,26 kg", shortName: "Gew. 7,26", code: "TGEW_07260", dlvID: "GEW", unit: .metrisch),
        Disciplin(name: "Gewichtwurf 7,5 kg", shortName: "Gew. 7,5", code: "TGEW_07500", dlvID: "GEW", unit: .metrisch),
        Disciplin(name: "Gewichtwurf 9,08 kg", shortName: "Gew. 9,08", code: "TGEW_09080", dlvID: "GEW", unit: .metrisch),
        Disciplin(name: "Gewichtwurf 10 kg", shortName: "Gew. 10", code: "TGEW_10000", dlvID: "GEW", unit: .metrisch),
        Disciplin(name: "Gewichtwurf 11,34 kg", shortName: "Gew. 11,34", code: "TGEW_11340", dlvID: "GEW", unit: .metrisch),
        Disciplin(name: "Gewichtwurf 12,5 kg", shortName: "Gew. 12,5", code: "TGEW_12500", dlvID: "GEW", unit: .metrisch),
        Disciplin(name: "Gewichtwurf 15,88 kg", shortName: "Gew. 15,88", code: "TGEW_15880", dlvID: "GEW", unit: .metrisch),
        Disciplin(name: "Diskuswurf", shortName: "Diskus", code: "TDIS", dlvID: "DIS", unit: .metrisch),
        Disciplin(name: "Diskuswurf 0,75 kg", shortName: "Diskus 0,7", code: "TDIS_0750", dlvID: "DIS", unit: .metrisch),
        Disciplin(name: "Diskuswurf 1 kg", shortName: "Diskus 1,0", code: "TDIS_1000", dlvID: "DIS", unit: .metrisch),
        Disciplin(name: "Diskuswurf 1,5 kg", shortName: "Diskus 1,5", code: "TDIS_1500", dlvID: "DIS", unit: .metrisch),
        Disciplin(name: "Diskuswurf 1,75 kg", shortName: "Diskus 1,7", code: "TDIS_1750", dlvID: "DIS", unit: .metrisch),
        Disciplin(name: "Diskuswurf 2 kg", shortName: "Diskus 2,0", code: "TDIS_2000", dlvID: "DIS", unit: .metrisch),
        Disciplin(name: "Hammerwurf", shortName: "Hammer", code: "THAM", dlvID: "HAM", unit: .metrisch),
        Disciplin(name: "Hammerwurf 2 kg", shortName: "Hammer 2", code: "THAM_2000", dlvID: "HAM", unit: .metrisch),
        Disciplin(name: "Hammerwurf 3 kg", shortName: "Hammer 3", code: "THAM_3000", dlvID: "HAM", unit: .metrisch),
        Disciplin(name: "Hammerwurf 4 kg", shortName: "Hammer 4", code: "THAM_4000", dlvID: "HAM", unit: .metrisch),
        Disciplin(name: "Hammerwurf 5 kg", shortName: "Hammer 5", code: "THAM_5000", dlvID: "HAM", unit: .metrisch),
        Disciplin(name: "Hammerwurf 6 kg", shortName: "Hammer 6", code: "THAM_6000", dlvID: "HAM", unit: .metrisch),
        Disciplin(name: "Hammerwurf 7,26 kg", shortName: "Hammer 7", code: "THAM_7260", dlvID: "HAM", unit: .metrisch),
        Disciplin(name: "Speerwurf", shortName: "Speer", code: "TSPE", dlvID: "SPE", unit: .metrisch),
        Disciplin(name: "Speerwurf 400 g", shortName: "Speer 400", code: "TSPE_0400", dlvID: "SPE", unit: .metrisch),
        Disciplin(name: "Speerwurf 500 g", shortName: "Speer 500", code: "TSPE_0500", dlvID: "SPE", unit: .metrisch),
        Disciplin(name: "Speerwurf 600 g", shortName: "Speer 600", code: "TSPE_0600", dlvID: "SPE", unit: .metrisch),
        Disciplin(name: "Speerwurf 700 g", shortName: "Speer 700", code: "TSPE_0700", dlvID: "SPE", unit: .metrisch),
        Disciplin(name: "Speerwurf 800 g", shortName: "Speer 800", code: "TSPE_0800", dlvID: "SPE", unit: .metrisch),
        Disciplin(name: "Schlagball", shortName: "SBall", code: "TSBAL_0080", dlvID: "SCH", unit: .metrisch),
        Disciplin(name: "Ballwurf", shortName: "Ball", code: "TBAL_0200", dlvID: "BAL", unit: .metrisch),
        Disciplin(name: "Schleuderball", shortName: "Schleudrb.", code: "TSLBAL", dlvID: "SBA", unit: .metrisch),
        Disciplin(name: "Schleuderball 0,8 kg", shortName: "Shldb. 0,8", code: "TSLBAL_0800", dlvID: "SBA", unit: .metrisch),
        Disciplin(name: "Schleuderball 1 kg", shortName: "Shldb. 1,0", code: "TSLBAL_1000", dlvID: "SBA", unit: .metrisch),
        Disciplin(name: "Schleuderball 1,5 kg", shortName: "Shldb. 1,5", code: "TSLBAL_1500", dlvID: "SBA", unit: .metrisch),
        Disciplin(name: "Steinstoß", shortName: "Stein", code: "TSTE", dlvID: "STE", unit: .metrisch),
        Disciplin(name: "Steinstoß 3 kg", shortName: "Stein 3,0", code: "TSTE_03000", dlvID: "STE", unit: .metrisch),
        Disciplin(name: "Steinstoß 5 kg", shortName: "Stein 5,0", code: "TSTE_05000", dlvID: "STE", unit: .metrisch),
        Disciplin(name: "Steinstoß 7,5 kg", shortName: "Stein 7,5", code: "TSTE_07500", dlvID: "STE", unit: .metrisch),
        Disciplin(name: "Steinstoß 10 kg", shortName: "Stein 10", code: "TSTE_10000", dlvID: "STE", unit: .metrisch),
        Disciplin(name: "Steinstoß 15 kg", shortName: "Stein 15", code: "TSTE_15000", dlvID: "STE", unit: .metrisch),
        Disciplin(name: "5er Sprunglauf", shortName: "5er Spglf.", code: "TFER", dlvID: "FER", unit: .metrisch),
        Disciplin(name: "Vortex (Heuler)", shortName: "Vortex", code: "TVOR", dlvID: "VOR", unit: .metrisch),
        Disciplin(name: "Keule", shortName: "Keule", code: "TKEULE", dlvID: "KLE", unit: .metrisch),
        Disciplin(name: "Keule 250 g", shortName: "Keule 250", code: "TKEULE_0250", dlvID: "KLE", unit: .metrisch),
        Disciplin(name: "Keule 500 g", shortName: "Keule 500", code: "TKEULE_0500", dlvID: "KLE", unit: .metrisch),
        Disciplin(name: "2-Kampf", shortName: "2-Kampf", code: "M2K", dlvID: "2-K", unit: .punkte),
        Disciplin(name: "2-Kampf Mannschaft", shortName: "2-K Man.", code: "M2KM", dlvID: "2-M", unit: .punkte),
        Disciplin(name: "3-Kampf", shortName: "3-Kampf", code: "M3K", dlvID: "3-K", unit: .punkte),
        Disciplin(name: "3-Kampf Mannschaft", shortName: "3-K Man.", code: "M3KM", dlvID: "3-M", unit: .punkte),
        Disciplin(name: "4-Kampf", shortName: "4-Kampf", code: "M4K", dlvID: "4-K", unit: .punkte),
        Disciplin(name: "4-Kampf Mannschaft", shortName: "4-K Man.", code: "M4KM", dlvID: "4-M", unit: .punkte),
        Disciplin(name: "5-Kampf", shortName: "5-Kampf", code: "M5K", dlvID: "5-K", unit: .punkte),
        Disciplin(name: "5-Kampf Mannschaft", shortName: "5-K Man.", code: "M5KM", dlvID: "5-M", unit: .punkte),
        Disciplin(name: "6-Kampf", shortName: "6-Kampf", code: "M6K", dlvID: "6-K", unit: .punkte),
        Disciplin(name: "6-Kampf Mannschaft", shortName: "6-K Man.", code: "M6KM", dlvID: "6-M", unit: .punkte),
        Disciplin(name: "7-Kampf", shortName: "7-Kampf", code: "M7K", dlvID: "7-K", unit: .punkte),
        Disciplin(name: "7-Kampf Mannschaft", shortName: "7-K Man.", code: "M7KM", dlvID: "7-M", unit: .punkte),
        Disciplin(name: "8-Kampf", shortName: "8-Kampf", code: "M8K", dlvID: "8-K", unit: .punkte),
        Disciplin(name: "8-Kampf Mannschaft", shortName: "8-K Man.", code: "M8KM", dlvID: "8-M", unit: .punkte),
        Disciplin(name: "9-Kampf", shortName: "9-Kampf", code: "M9K", dlvID: "9-K", unit: .punkte),
        Disciplin(name: "9-Kampf Mannschaft", shortName: "9-K Man.", code: "M9KM", dlvID: "9-M", unit: .punkte),
        Disciplin(name: "10-Kampf", shortName: "10-Kampf", code: "M10K", dlvID: "10-K", unit: .punkte),
        Disciplin(name: "10-Kampf Mannschaft", shortName: "10-K Man.", code: "M10KM", dlvID: "10-M", unit: .punkte),
        Disciplin(name: "Block Sprint/Sprung", shortName: "Block S/S", code: "MBLS", dlvID: "BLS", unit: .punkte),
        Disciplin(name: "Block Lauf", shortName: "Block L", code: "MBLL", dlvID: "BLL", unit: .punkte),
        Disciplin(name: "Block Wurf", shortName: "Block W", code: "MBLW", dlvID: "BLW", unit: .punkte),
        Disciplin(name: "Block Mannschaft", shortName: "Block Man.", code: "MBLM", dlvID: "BLM", unit: .punkte),
        Disciplin(name: "Block Einzel", shortName: "Block E", code: "MBLE", dlvID: "BLE", unit: .punkte),
        Disciplin(name: "Block Basis", shortName: "Block B", code: "MBLB", dlvID: "BLB", unit: .punkte),
        Disciplin(name: "Wurf 3-Kampf", shortName: "Wrfr 3K", code: "MW3K", dlvID: "W3-K", unit: .punkte),
        Disciplin(name: "Wurf 4-Kampf", shortName: "Wrfr 4K", code: "MW4K", dlvID: "W4-K", unit: .punkte),
        Disciplin(name: "Wurf 5-Kampf", shortName: "Wrfr 5K", code: "MW5K", dlvID: "W5-K", unit: .punkte),
        Disciplin(name: "Wurf 5-Kampf Mannschaft", shortName: "Wrfr5K Man", code: "MW5KM", dlvID: "W5-M", unit: .punkte),
        Disciplin(name: "Wurf 6-Kampf", shortName: "Wrfr 6K", code: "MW6K", dlvID: "W6-K", unit: .punkte),
        Disciplin(name: "Kinderleichtathletik", shortName: "KiLa", code: "KKILA", dlvID: "KILA", unit: .punkte),
        Disciplin(name: "KiLa Sprint", shortName: "KiLa Sprint", code: "KKILA_SPRINT", dlvID: "KISP", unit: .punkte),
        Disciplin(name: "KiLa Hindernissprint", shortName: "KiLa Hin.Sprint.", code: "KKILA_HINDERNIS", dlvID: "KIHI", unit: .punkte),
        Disciplin(name: "KiLa Rundenstaffel U12", shortName: "KiLa Rndn.Staff.", code: "KKILA_STAFFEL", dlvID: "KISF", unit: .punkte),
        Disciplin(name: "KiLa Ausdauerlauf", shortName: "KiLa Lauf", code: "KKILA_LAUF", dlvID: "KILF", unit: .punkte),
        Disciplin(name: "KiLa Weitsprung", shortName: "KiLa Weit", code: "KKILA_WEIT", dlvID: "KIWE", unit: .punkte),
        Disciplin(name: "KiLa Hochsprung", shortName: "KiLa Hoch", code: "KKILA_HOCH", dlvID: "KIHO", unit: .punkte),
        Disciplin(name: "KiLa Mehrfachsprung", shortName: "KiLa Mf.Sprg.", code: "KKILA_MEHRFACHSPRUNG", dlvID: "KIMS", unit: .punkte),
        Disciplin(name: "KiLa Stabsprung", shortName: "KiLa Stabsprg.", code: "KKILA_STABSPRUNG", dlvID: "KISS", unit: .punkte),
        Disciplin(name: "KiLa Schlagwurf", shortName: "KiLa S-Wurf", code: "KKILA_WURF", dlvID: "KIWU", unit: .punkte),
        Disciplin(name: "KiLa Stoßen", shortName: "KiLa Stossen", code: "KKILA_STOSS", dlvID: "KIST", unit: .punkte),
        Disciplin(name: "KiLa Drehwurf", shortName: "KiLa Drehwurf", code: "KKILA_DREHWURF", dlvID: "KIDW", unit: .punkte),
        Disciplin(name: "KiLa Gehen", shortName: "KiLa Gehen", code: "KKILA_GEHEN", dlvID: "KIGE", unit: .punkte),
        Disciplin(name: "Kinderleichtathletik Mannschaft", shortName: "KiLa Man.", code: "KKILAM", dlvID: "KILM", unit: .punkte),
        Disciplin(name: "Viertelstundenlauf", shortName: "1/4Stdlauf", code: "AVSTD", dlvID: "VSTD", unit: .metrisch),
        Disciplin(name: "Halbstundenlauf", shortName: "1/2Stdlauf", code: "AHSTD", dlvID: "HSTD", unit: .metrisch),
        Disciplin(name: "Stundenlauf", shortName: "Std.-lauf", code: "ASTD", dlvID: "STD", unit: .metrisch),
        Disciplin(name: "Lauf auf Zeit", shortName: "Lauf auf Zeit", code: "ALAUFAUFZEIT", dlvID: "LFAZ", unit: .metrisch),
    ]
}




